// Generado por web_i18n/i18n_rebuild.js (fr) a partir de web/js/epocas_fichas.js. No editar a mano: editar la memoria tm/fr.json y regenerar.
const EPOCAS_FICHAS = {
 "ant": {
  "anos": "Du VIe siècle av. J.-C. au Ve siècle apr. J.-C. (par convention, jusqu’à la chute de Rome en 476).",
  "abre": "<p>Dans les cités grecques d’Ionie, comme Milet, des penseurs commencent à expliquer la nature sans recourir aux dieux : c’est le passage <strong>du mythe au logos</strong>. Selon Hérodote, Thalès aurait prédit une éclipse de soleil (celle de 585 av. J.-C.). Le commerce, le contact avec l’Égypte et Babylone, l’écriture alphabétique et des cités où aucune caste de prêtres ne contrôle le savoir y contribuent.</p>",
  "social": "<p>La vie tourne autour de la <strong>polis</strong>, la cité-État. Seuls les hommes libres nés dans la cité sont citoyens : les femmes, les étrangers résidents (métèques) et les esclaves en sont exclus. Le temps libre pour penser (<em>scholé</em>, d’où vient « école ») repose en grande partie sur le travail des esclaves. Les enfants sont éduqués avec les poèmes d’Homère, et au Ve siècle av. J.-C. les sophistes commencent à se faire payer pour enseigner l’art de parler en public.</p>\n<p>Après Alexandre, le centre du savoir se déplace vers <strong>Alexandrie</strong>, avec son Musée et sa Bibliothèque (IIIe siècle av. J.-C.), puis vers Rome, où la philosophie grecque devient une partie de l’éducation des élites.</p>",
  "politico": "<p>Les cités sont indépendantes et souvent rivales. Athènes développe la <strong>démocratie</strong> après les réformes de Clisthène (508 av. J.-C.), vainc les Perses lors des guerres médiques (490-479 av. J.-C.) et perd la guerre du Péloponnèse contre Sparte (431-404 av. J.-C.) ; peu après, elle condamne Socrate à mort (399 av. J.-C.).</p>\n<p>Alexandre le Grand crée un immense empire (336-323 av. J.-C.) qui se divise en royaumes hellénistiques, lesquels finissent par être absorbés par <strong>Rome</strong>, république puis empire (à partir de 27 av. J.-C.). En 380, le christianisme devient la religion officielle de l’Empire, et en 476 l’Empire romain d’Occident tombe.</p>",
  "ciencia": "<p>Les Grecs transforment les techniques de calcul de l’Égypte et de Babylone en <strong>mathématiques démonstratives</strong> : les pythagoriciens et, vers 300 av. J.-C., les <em>Éléments</em> d’Euclide. Ératosthène calcule la circonférence de la Terre (IIIe siècle av. J.-C.) ; Aristarque propose que la Terre tourne autour du Soleil, mais c’est le modèle avec la Terre au centre, que Ptolémée systématise au IIe siècle, qui s’imposera. La médecine hippocratique cherche des causes naturelles aux maladies, et Aristote fonde la biologie en observant les animaux.</p>\n<p>La technique, en revanche, progresse peu : avec une main-d’œuvre servile abondante, on s’intéresse à peine à économiser l’effort grâce aux machines.</p>",
  "pensamiento": "<ul>\n<li><strong>Présocratiques :</strong> ils cherchent l’<em>arkhé</em>, le principe de la nature (<em>physis</em>) : l’eau, l’air, les nombres, les atomes.</li>\n<li><strong>Tournant vers l’être humain :</strong> les sophistes discutent pour savoir si les lois sont naturelles ou conventionnelles, et Socrate demande ce que sont la justice et la vertu.</li>\n<li><strong>Grands systèmes :</strong> Platon (les Idées) et Aristote (la forme dans les choses) organisent tous les savoirs.</li>\n<li><strong>Écoles hellénistiques :</strong> cyniques, épicuriens, stoïciens et sceptiques se demandent surtout comment vivre dans la sérénité dans un monde incertain.</li>\n<li><strong>Fin de l’époque :</strong> le néoplatonisme de Plotin et la rencontre avec le christianisme. Tertullien demandait ce qu’Athènes avait à voir avec Jérusalem ; d’autres, comme Augustin, feront de la philosophie grecque une alliée.</li>\n</ul>",
  "rupturas": "<p>La philosophie antique ne disparaît pas : le christianisme l’absorbe et la transforme. Augustin d’Hippone lit la foi avec des yeux platoniciens. En 529, l’empereur Justinien interdit aux païens d’enseigner la philosophie à Athènes, et le savoir grec reste vivant surtout à Byzance et, à partir du VIIIe siècle, dans le monde islamique, où Aristote est traduit en arabe et commenté pendant des siècles.</p>",
  "trampa": "<p>« Les Grecs ont inventé la philosophie à partir de rien. » Ils se sont abreuvés à l’Égypte et à Babylone, et ils n’ont pas été les seuls : aux mêmes siècles, Bouddha enseignait en Inde et Confucius en Chine. Ce qui est propre aux Grecs, c’est d’avoir fait de la discussion rationnelle et publique une méthode. Et un autre piège : la philosophie antique ne se réduit pas à Platon et Aristote, c’est près de douze siècles d’écoles différentes.</p>"
 },
 "med": {
  "anos": "Du Ve siècle au XVe siècle (dans l’axe chronologique du département, de 476 à 1492).",
  "abre": "<p>En 476, l’Empire romain d’Occident tombe. Au milieu de la ruine des villes, l’<strong>Église</strong> devient l’institution qui conserve l’écriture, les livres et l’enseignement. Augustin d’Hippone, qui meurt en 430 alors que les Vandales assiègent sa ville, laisse par écrit la grande synthèse entre philosophie grecque et foi chrétienne qui guidera les siècles suivants.</p>",
  "social": "<p>C’est une société <strong>d’ordres</strong> : vers l’an 1000, on la décrivait comme formée de ceux qui prient, de ceux qui combattent et de ceux qui travaillent. La plupart vivent à la campagne, soumis à un seigneur (la <strong>féodalité</strong>). Les monastères copient et conservent les livres anciens ; les couvents sont aussi l’un des rares endroits où les femmes peuvent étudier et écrire, comme Hildegarde de Bingen.</p>\n<p>À partir du XIe siècle, les villes et le commerce renaissent, et naissent les <strong>universités</strong> (Bologne, Paris, Oxford, Salamanque). La peste noire (1347-1351) tue une part énorme de la population européenne, peut-être un tiers.</p>",
  "politico": "<p>Après Rome surgissent les royaumes germaniques ; Charlemagne est couronné empereur en l’an 800. À l’est subsiste l’<strong>Empire byzantin</strong>, et à partir du VIIe siècle l’islam s’étend de l’Arabie à la péninsule Ibérique (al-Andalus, à partir de 711). Papes et empereurs se disputent pendant des siècles pour savoir qui a le dernier mot, et les croisades (1096-1291) opposent chrétiens et musulmans.</p>\n<p>L’époque se clôt sur deux dates : la chute de Constantinople aux mains des Ottomans (1453) et, en 1492, la prise de Grenade et l’arrivée de Colomb en Amérique.</p>",
  "ciencia": "<p>Dans la <strong>Bagdad</strong> des VIIIe-Xe siècles, on traduit en arabe Aristote, Euclide, Ptolémée et Galien. Al-Khwârizmî donne son nom à l’<strong>algèbre</strong> et à l’algorithme ; Avicenne écrit le <em>Canon de la médecine</em>, étudié en Europe pendant des siècles. Aux XIIe et XIIIe siècles, à Tolède et ailleurs, ce savoir est traduit en latin, et l’Europe adopte les chiffres indo-arabes et le zéro.</p>\n<p>La technique progresse plus qu’on ne le croit d’ordinaire : la charrue lourde, les moulins, l’horloge mécanique et, vers 1450, l’<strong>imprimerie</strong> à caractères mobiles de Gutenberg.</p>",
  "pensamiento": "<ul>\n<li><strong>Foi et raison :</strong> le grand problème de l’époque est de savoir comment concilier ce que l’on croit et ce que l’on démontre.</li>\n<li><strong>Patristique :</strong> les Pères de l’Église, Augustin en tête, pensent la foi avec des outils platoniciens.</li>\n<li><strong>Scolastique :</strong> dans les écoles et les universités, on raisonne selon une méthode rigoureuse (lecture, question, dispute). Anselme propose son argument ontologique ; Thomas d’Aquin harmonise Aristote avec la foi.</li>\n<li><strong>Philosophie en arabe et en hébreu :</strong> Avicenne, Averroès et Maïmonide pensent les mêmes problèmes depuis l’islam et le judaïsme.</li>\n<li><strong>Les universaux :</strong> l’« être humain » existe-t-il en plus de chaque être humain ? Abélard et Ockham répondent que ce sont des noms ou des concepts.</li>\n</ul>",
  "rupturas": "<p>Au XIVe siècle, Ockham sépare la foi de la raison : ce que l’on croit ne peut pas se démontrer, et le rasoir qui porte son nom retranche les entités inutiles. La peste, le Grand Schisme d’Occident (1378-1417), avec deux et même trois papes à la fois, et la critique de la scolastique par les humanistes italiens ouvrent la voie à la Renaissance. L’imprimerie fera le reste.</p>",
  "trampa": "<p>« Le Moyen Âge fut une époque obscure. » Le nom a été inventé par les humanistes pour la mépriser, mais c’est alors que sont nées les universités, que la logique a atteint un très haut niveau et que l’on a traduit la moitié du savoir antique. Et non : les savants médiévaux ne croyaient pas que la Terre était plate ; sa forme sphérique s’enseignait dans les universités, par exemple avec le <em>Traité de la sphère</em> de Sacrobosco (XIIIe siècle).</p>"
 },
 "ren": {
  "anos": "Du milieu du XVe siècle à la fin du XVIe siècle (dans l’axe chronologique du département, de 1492 à 1600).",
  "abre": "<p>Trois nouveautés changent le monde en quelques années : l’<strong>imprimerie</strong> (vers 1450), qui multiplie les livres ; l’arrivée en Italie de savants et de manuscrits grecs venus de Byzance ; et l’arrivée de Colomb en Amérique (1492), qui montre que le monde connu des Anciens n’en était qu’une partie.</p>",
  "social": "<p>Les villes italiennes, comme Florence ou Venise, s’enrichissent grâce au commerce et à la banque, et des familles comme les Médicis paient des artistes et des savants (le <strong>mécénat</strong>). Les livres imprimés touchent plus de gens, et apparaît la figure de l’humaniste qui vit d’écrire, d’enseigner ou de conseiller les princes.</p>\n<p>La conquête de l’Amérique détruit des sociétés entières et ouvre le commerce atlantique des personnes réduites en esclavage. Elle provoque aussi un débat philosophique : lors de la controverse de Valladolid (1550-1551), Bartolomé de las Casas et Juan Ginés de Sepúlveda discutent pour savoir si les peuples indigènes peuvent être soumis.</p>",
  "politico": "<p>Les <strong>États modernes</strong> se constituent, avec des rois qui concentrent le pouvoir (les Rois Catholiques, la France, l’Angleterre). L’Italie, divisée en petits États, est le champ de bataille des grandes puissances : c’est dans ce contexte que Machiavel écrit <em>Le Prince</em> (1513).</p>\n<p>En 1517, Luther publie ses 95 thèses et la <strong>Réforme</strong> protestante commence. L’Europe se divise sur le plan religieux : guerres de religion, paix d’Augsbourg (1555), qui laisse à chaque prince le choix de la religion de ses sujets, et réponse catholique du concile de Trente (1545-1563).</p>",
  "ciencia": "<p>En 1543 paraissent deux livres décisifs : <em>Des révolutions des sphères célestes</em> de Copernic, qui place le Soleil au centre, et l’anatomie de Vésale, qui corrige Galien à partir de dissections. Léonard de Vinci unit art, observation et ingénierie. La <strong>révolution scientifique</strong> commence ici et culminera au XVIIe siècle avec Kepler, Galilée, Harvey et Newton.</p>",
  "pensamiento": "<ul>\n<li><strong>Humanisme :</strong> retour aux textes classiques dans leur langue originale et confiance dans la dignité de l’être humain, capable de se faire lui-même (Pic de la Mirandole, <em>Discours sur la dignité de l’homme</em>, 1486).</li>\n<li><strong>Critique et tolérance :</strong> Érasme se moque des abus de son temps dans l’<em>Éloge de la folie</em> (1511) et défend une religion intérieure et pacifique.</li>\n<li><strong>Utopies :</strong> Thomas More (<em>L’Utopie</em>, 1516) et, plus tard, Campanella imaginent des sociétés justes pour critiquer les sociétés réelles.</li>\n<li><strong>Réalisme politique :</strong> Machiavel sépare la politique de la morale religieuse.</li>\n<li><strong>Une nature infinie :</strong> Nicolas de Cues et Giordano Bruno, brûlé par l’Inquisition en 1600, pensent un univers sans limites.</li>\n</ul>",
  "rupturas": "<p>À la fin du XVIe siècle, l’autorité de l’Église est divisée et celle d’Aristote contestée. Montaigne doute de presque tout. La question dont hérite l’époque moderne est de savoir où trouver un fondement sûr pour la connaissance : Francis Bacon propose une méthode fondée sur l’expérience (<em>Novum organum</em>, 1620) et Descartes, sur la raison (<em>Discours de la méthode</em>, 1637).</p>\n<p>Dans Illustres, Descartes apparaît à cette époque parce que l’axe chronologique du département la clôt en 1600 et qu’il est né en 1596 ; mais son œuvre ouvre la philosophie moderne.</p>",
  "trampa": "<p>« À la Renaissance, la science a vaincu la religion. » Copernic était chanoine de l’Église, et Kepler et Galilée étaient croyants. De plus, à côté de la science nouvelle ont fleuri la magie, l’astrologie et l’alchimie, que beaucoup d’humanistes prenaient très au sérieux.</p>"
 },
 "mod": {
  "anos": "Le XVIIe siècle (dans l’axe chronologique du département, la philosophie moderne va de 1600 à 1800 ; les Lumières ont ici leur propre fiche).",
  "abre": "<p>La <strong>révolution scientifique</strong> change la manière de connaître. Galilée braque sa lunette vers le ciel (1610) et soutient que le livre de la nature est écrit en langue mathématique (<em>L’Essayeur</em>, 1623). L’autorité des Anciens étant en crise, Descartes cherche à repartir de zéro, à partir d’une vérité dont on ne puisse douter (<em>Discours de la méthode</em>, 1637).</p>",
  "social": "<p>C’est un siècle de crise : la <strong>guerre de Trente Ans</strong> (1618-1648) ravage l’Europe centrale, et les épidémies et les mauvaises récoltes sont fréquentes. Les Provinces-Unies, république marchande et relativement tolérante, accueillent des penseurs persécutés ou gênants : Descartes et Spinoza, que sa communauté juive a expulsé en 1656, y ont vécu.</p>\n<p>Les savants forment une « république des lettres » qui s’écrit à travers toute l’Europe, comme dans les lettres de Descartes et d’Élisabeth de Bohême, et naissent les premières <strong>académies scientifiques</strong> : la Royal Society de Londres (1660) et l’Académie des sciences de Paris (1666).</p>",
  "politico": "<p>L’<strong>absolutisme</strong> triomphe : le roi concentre tout le pouvoir, comme Louis XIV en France (règne de 1643 à 1715). La paix de Westphalie (1648) organise l’Europe en États souverains. L’Angleterre fait exception : une guerre civile (1642-1651) se termine par l’exécution du roi Charles Ier en 1649, et la Glorieuse Révolution (1688-1689) limite le pouvoir de la couronne. Hobbes écrit le <em>Léviathan</em> (1651) après la guerre ; Locke, ses <em>Deux traités du gouvernement civil</em> (1689) après la révolution.</p>",
  "ciencia": "<p>Kepler découvre que les planètes décrivent des ellipses ; Harvey démontre la circulation du sang (1628) ; le microscope révèle un monde invisible (Hooke, <em>Micrographia</em>, 1665). Newton et Leibniz inventent séparément le <strong>calcul infinitésimal</strong>, et Newton réunit la physique du ciel et celle de la Terre en une seule loi de la gravitation (1687).</p>\n<p>L’image dominante est celle du <strong>mécanisme</strong> : le monde fonctionne comme une grande horloge, dont les pièces se meuvent par contact selon des lois mathématiques.</p>",
  "pensamiento": "<ul>\n<li><strong>La méthode et la certitude :</strong> avant de savoir ce qu’il y a, il faut savoir comment nous pouvons le connaître.</li>\n<li><strong>Rationalisme :</strong> Descartes, Spinoza, Malebranche et Leibniz ont confiance dans des idées que la raison connaît par elle-même.</li>\n<li><strong>Empirisme :</strong> Locke et Berkeley soutiennent que toute connaissance provient de l’expérience ; Hume la poussera à la limite au siècle suivant.</li>\n<li><strong>Substance :</strong> combien y en a-t-il ? Deux pour Descartes (esprit et matière), une pour Spinoza, une infinité de monades pour Leibniz, seulement la matière pour Hobbes.</li>\n<li><strong>Contrat social et tolérance :</strong> Hobbes et Locke fondent le pouvoir sur un pacte ; Spinoza (1670) et Locke (1689) défendent la liberté de pensée et la tolérance religieuse.</li>\n</ul>",
  "rupturas": "<p>Newton et Locke deviennent les modèles de la génération suivante : Voltaire les fait connaître en France dans ses <em>Lettres philosophiques</em> (1734). La confiance dans la raison, que le XVIIe siècle appliquait surtout à la nature, les Lumières l’étendront à la société, à la politique et à la religion.</p>",
  "trampa": "<p>« Rationalistes et empiristes formaient deux équipes adverses. » L’étiquette a été posée après coup par les historiens. Tous se lisaient et se répondaient : Locke discute avec Descartes, et Leibniz a consacré un livre entier à répondre à Locke (<em>Nouveaux essais sur l’entendement humain</em>). Et presque tous partageaient la confiance dans les mathématiques et dans la nouvelle physique.</p>"
 },
 "ilu": {
  "anos": "De la fin du XVIIe siècle (vers 1680) à 1800, environ.",
  "abre": "<p>La révolution scientifique culmine avec les <em>Principes mathématiques de la philosophie naturelle</em> de Newton (1687) : l’univers obéit à des lois que la raison peut découvrir. L’année suivante, la Glorieuse Révolution anglaise (1688-1689) soumet le roi à une déclaration des droits du Parlement. Raison et liberté politique sont les deux idées que l’époque portera le plus loin.</p>",
  "social": "<p>Une <strong>bourgeoisie</strong> de commerçants, de médecins, d’avocats et de fonctionnaires se développe : elle lit, discute et veut avoir de l’influence. Naissent des lieux de conversation en dehors de la cour et de l’Église : les <strong>cafés</strong>, les académies, les loges et les <strong>salons</strong>, beaucoup tenus par des femmes, comme celui de Madame Geoffrin à Paris. Les journaux et les livres bon marché se multiplient, et apparaît quelque chose de nouveau : l’<strong>opinion publique</strong>.</p>\n<p>Mais les Lumières ont été l’affaire de minorités : la majorité de la population était paysanne et ne savait pas lire. Et la richesse des ports européens dépendait en grande partie du commerce atlantique des personnes réduites en esclavage.</p>",
  "politico": "<p>Presque toute l’Europe vit sous des <strong>monarchies absolues</strong>. Certains rois adoptent des réformes inspirées des Lumières sans céder de pouvoir (ce qu’on appelle le <strong>despotisme éclairé</strong> : Frédéric II de Prusse, Catherine II de Russie, Charles III en Espagne). La censure reste active : l’<em>Encyclopédie</em> fut interdite en France en 1759 et continua de paraître en cachette.</p>\n<p>À la fin du siècle, deux révolutions portent les idées dans la politique : l’<strong>indépendance des États-Unis</strong> (1776), avec sa déclaration des droits, et la <strong>Révolution française</strong> (1789), avec la <em>Déclaration des droits de l’homme et du citoyen</em>.</p>",
  "ciencia": "<p>Newton devient le modèle de tout savoir : observer, mesurer et chercher des lois. Linné classe les êtres vivants (<em>Systema naturae</em>, 1735) ; Lavoisier fonde la chimie moderne (<em>Traité élémentaire de chimie</em>, 1789) ; Jenner met à l’épreuve le premier vaccin, contre la variole (1796). En Grande-Bretagne, la machine à vapeur de Watt (brevetée en 1769) ouvre la <strong>révolution industrielle</strong>.</p>\n<p>L’<em>Encyclopédie</em> de Diderot et d’Alembert (1751-1772) veut rassembler tout le savoir, y compris celui des métiers, avec des planches d’ateliers et de machines : la connaissance technique devient digne de la philosophie.</p>",
  "pensamiento": "<p>L’idée centrale a été résumée par Kant en 1784 : les Lumières sont la sortie de l’être humain de la minorité dont il est lui-même responsable ; leur devise, <em>sapere aude</em>, « aie le courage de te servir de ton propre entendement ! » (<em>Qu’est-ce que les Lumières ?</em>). De là leurs grands traits :</p>\n<ul>\n<li><strong>Raison critique :</strong> rien n’est accepté par tradition ou par autorité sans examen, pas même la raison elle-même (Hume, Kant).</li>\n<li><strong>Progrès :</strong> le savoir et l’éducation peuvent améliorer la vie humaine (Rousseau, <em>Émile</em>, 1762).</li>\n<li><strong>Tolérance</strong> religieuse et critique de la superstition (Voltaire, <em>Traité sur la tolérance</em>, 1763). Beaucoup d’hommes des Lumières sont déistes : ils croient en un Dieu créateur, mais pas aux religions révélées.</li>\n<li><strong>Droits et séparation des pouvoirs</strong> face à l’absolutisme (Montesquieu, <em>De l’esprit des lois</em>, 1748 ; Rousseau, <em>Du contrat social</em>, 1762).</li>\n<li><strong>Bonheur et utilité :</strong> la morale se pense à partir du sentiment (Hume) ou des conséquences (Bentham), et l’économie comme un savoir à part entière (Adam Smith, <em>La Richesse des nations</em>, 1776).</li>\n<li>Premières voix pour l’<strong>égalité des femmes</strong> : Olympe de Gouges (1791) et Mary Wollstonecraft (1792).</li>\n</ul>",
  "rupturas": "<p>Les Lumières ne s’achèvent pas d’un coup. En Allemagne, Hamann et Herder leur reprochent d’oublier le sentiment, la langue et l’histoire de chaque peuple, et le <strong>romantisme</strong> reprend cette critique. La Terreur de la Révolution française (1793-1794) amène à se demander si la raison peut refaire toute une société. Kant clôt l’époque et l’examine à la fois : ses <em>Critiques</em> marquent les limites de la raison.</p>\n<p>D’autres courants se poursuivent au XIXe siècle : l’<strong>utilitarisme</strong> et le <strong>libéralisme</strong> de Bentham et de Mill (c’est pourquoi, dans Illustres, ils figurent à cette époque), et la foi dans le progrès, dont héritent Hegel et Marx. Au XXe siècle, Adorno et Horkheimer (<em>La Dialectique de la raison</em>, 1944) se demandent pourquoi la raison des Lumières n’a pas empêché la barbarie.</p>",
  "trampa": "<p>« Les Lumières furent françaises. » Paris en fut la capitale la plus visible, mais il y a eu des Lumières écossaises (Hume, Smith), allemandes (Kant, Lessing, Mendelssohn), espagnoles (Feijoo, Jovellanos) et américaines (Franklin, Jefferson). Et « homme des Lumières » ne veut pas dire « athée » : Holbach l’était, mais Voltaire était déiste et Kant défendait une foi rationnelle.</p>"
 },
 "con": {
  "nombre": "Époque contemporaine I : le XIXe siècle",
  "block": "con",
  "nacidos": [
   1700,
   1849
  ],
  "temasHF": [
   21
  ],
  "anos": "De la fin du XVIIIe siècle à la Première Guerre mondiale (de 1800 à 1914 environ).",
  "abre": "<p>La Révolution française et les guerres de Napoléon changent la carte politique de l’Europe, et la <strong>révolution industrielle</strong> change la manière de vivre et de travailler. En philosophie, Kant a laissé ouverte la question des limites de la raison, et l’idéalisme allemand tente de les dépasser : Hegel publie la <em>Phénoménologie de l’esprit</em> en 1807.</p>",
  "social": "<p>Les usines attirent des millions de personnes des campagnes vers les villes. Le <strong>prolétariat</strong> apparaît, avec des journées de travail interminables et le travail des enfants, comme le décrivent les romans de Dickens, et avec lui le mouvement ouvrier, les syndicats et les socialismes : ceux qu’on appelle utopiques (Owen, Fourier, Saint-Simon) et celui de Marx et Engels (<em>Manifeste du parti communiste</em>, 1848). La bourgeoisie devient la classe dirigeante, et l’école et la presse touchent des couches de plus en plus larges de la population.</p>",
  "politico": "<p>C’est le siècle des révolutions libérales (1830, 1848), des constitutions et des <strong>nationalismes</strong> : l’Italie s’unifie en 1861 et l’Allemagne en 1871. Les puissances européennes se partagent l’Afrique et une grande partie de l’Asie en <strong>empires coloniaux</strong> (conférence de Berlin, 1884-1885). L’esclavage est peu à peu aboli : dans l’Empire britannique en 1833, aux États-Unis en 1865 après une guerre civile, dans la Cuba espagnole en 1886.</p>",
  "ciencia": "<p>Darwin explique l’évolution des espèces par la sélection naturelle (<em>De l’origine des espèces</em>, 1859) et Mendel découvre les lois de l’hérédité (1866). Faraday et Maxwell unifient l’électricité et le magnétisme ; Pasteur démontre le rôle des microbes dans les maladies. Le chemin de fer, le télégraphe et l’électricité transforment la vie quotidienne. Boole et Frege commencent à faire de la logique une branche des mathématiques.</p>",
  "pensamiento": "<ul>\n<li><strong>Idéalisme et romantisme :</strong> Fichte, Schelling et Hegel pensent la réalité comme le déploiement de l’esprit ; Novalis, Schlegel et Hölderlin revendiquent le sentiment, l’art et l’histoire de chaque peuple.</li>\n<li><strong>Positivisme :</strong> Comte soutient que le savoir culmine dans la science positive, fondée sur des faits observables.</li>\n<li><strong>Utilitarisme et libéralisme :</strong> Mill défend la liberté individuelle face à l’État et face à la pression de la majorité (<em>De la liberté</em>, 1859).</li>\n<li><strong>Socialisme et anarchisme :</strong> Marx, Proudhon et Kropotkine critiquent la propriété et le capitalisme depuis des positions différentes.</li>\n<li><strong>Soupçon :</strong> Marx et Nietzsche cherchent derrière les idées les intérêts économiques ou la volonté de puissance.</li>\n</ul>",
  "rupturas": "<p>Le XIXe siècle croit au <strong>progrès</strong> : les expositions universelles présentent des machines toujours plus étonnantes. Mais des fissures grandissent en son sein : Nietzsche annonce la « mort de Dieu » (1882), Freud explore un inconscient que la raison ne contrôle pas (<em>L’Interprétation du rêve</em>, 1900) et la physique classique commence à vaciller (Einstein, 1905). La Première Guerre mondiale (1914) brise définitivement cette confiance.</p>",
  "trampa": "<p>« Contemporain veut dire d’aujourd’hui. » En histoire, l’époque contemporaine commence à la fin du XVIIIe siècle : Hegel et Marx sont des philosophes « contemporains » même s’ils ont vécu il y a deux siècles. C’est pourquoi, sur ce site, l’époque est divisée en deux fiches : le XIXe siècle, et les XXe et XXIe siècles.</p>"
 },
 "con2": {
  "nombre": "Époque contemporaine II : XXe et XXIe siècles",
  "block": "con",
  "nacidos": [
   1850,
   2100
  ],
  "temasHF": [
   22,
   23,
   24,
   25,
   26,
   27
  ],
  "anos": "De la Première Guerre mondiale (1914) à aujourd’hui.",
  "abre": "<p>La <strong>Première Guerre mondiale</strong> (1914-1918), avec des millions de morts dans les tranchées et des armes fabriquées en série, brise la confiance du XIXe siècle dans le progrès. En 1917, la révolution russe promet une société sans classes. Le siècle commence en se demandant ce qui a échoué dans la civilisation qui se croyait la plus avancée.</p>",
  "social": "<p>La <strong>société de masse</strong> arrive : grandes villes, consommation, cinéma, radio et télévision. Les femmes conquièrent le droit de vote (en Espagne, en 1931) et l’école touche presque tout le monde. Dans la seconde moitié du siècle, l’<strong>État-providence</strong> se répand en Europe, avec une santé et des retraites publiques.</p>\n<p>Aujourd’hui, nous vivons dans un monde <strong>mondialisé</strong> et connecté par internet, avec d’énormes inégalités, de grandes migrations et une crise écologique qui oblige à repenser le progrès.</p>",
  "politico": "<p>Entre les deux guerres mondiales surgissent les <strong>totalitarismes</strong> (fascisme, nazisme, stalinisme). La Seconde Guerre mondiale (1939-1945) s’achève avec la Shoah et les bombes atomiques d’Hiroshima et de Nagasaki. Ensuite naissent l’ONU et la Déclaration universelle des droits de l’homme (1948), la guerre froide commence et l’Asie et l’Afrique se décolonisent.</p>\n<p>En Espagne, la dictature franquiste (1939-1975) envoie en exil de nombreux penseurs, comme María Zambrano. La chute du mur de Berlin (1989) clôt la guerre froide ; le XXIe siècle apporte la crise financière de 2008, la pandémie de covid-19 (2020) et de nouvelles guerres.</p>",
  "ciencia": "<p>Einstein (relativité) et la mécanique quantique changent l’idée d’espace, de temps et de matière. En 1953, la structure de l’ADN est décrite, à partir de données de Rosalind Franklin. Turing (1936) et Shannon (1948) posent les bases de l’informatique. L’énergie nucléaire, le voyage sur la Lune (1969), internet et l’intelligence artificielle montrent une puissance technique énorme, qui oblige à s’interroger sur ses limites.</p>",
  "pensamiento": "<ul>\n<li><strong>Psychanalyse :</strong> Freud montre que nous ne sommes pas tout à fait maîtres de notre esprit.</li>\n<li><strong>Existence et phénoménologie :</strong> Heidegger, Sartre, Beauvoir et Camus partent de l’existence concrète, de la liberté et de l’angoisse.</li>\n<li><strong>Tournant linguistique :</strong> Wittgenstein et la philosophie analytique examinent le langage ; Popper et Kuhn, la science.</li>\n<li><strong>Théorie critique :</strong> l’École de Francfort (Horkheimer, Adorno, Habermas) analyse la société de masse.</li>\n<li><strong>Philosophie en Espagne :</strong> Unamuno, Ortega et Zambrano ; en basque, Txillardegi et Azurmendi.</li>\n<li><strong>Débats d’aujourd’hui :</strong> féminisme (Beauvoir, Butler), postmodernité (Lyotard, Foucault, Derrida), justice (Rawls), écologie (Yayo Herrero), technologie et esprit (Han, Bostrom, Chalmers).</li>\n</ul>",
  "rupturas": "<p>C’est une époque qui n’est pas terminée, avec plusieurs coupures internes. Auschwitz et Hiroshima obligent à demander ce qu’a fait la raison (Adorno, Arendt) ; en 1979, Lyotard annonce la fin des « grands récits ». Les questions ouvertes aujourd’hui, comme l’intelligence artificielle, la crise climatique ou la désinformation, ouvrent peut-être déjà une autre époque que nous ne savons pas encore nommer.</p>",
  "trampa": "<p>« Dans la philosophie actuelle, tout se vaut. » Qu’il y ait de nombreux courants ne signifie pas que n’importe quelle opinion vaille : chacun discute avec les autres en donnant des raisons. Et « postmoderne » n’est pas une insulte ni ne veut dire « très moderne » : c’est une thèse précise sur la fin des grands récits, qui a aussi ses critiques, comme Habermas.</p>"
 }
};
